services:
  mysql:
    image: mysql:latest
    container_name: mysql_for_todolist
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Dist050427
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
