[server]
port = "8080"

[database]
host = "localhost"
port = "3306"
user = "root"
password = "050427"
dbname = "todo_list"

[jwt]
secret = "your_jwt_secret_key"
expire = 24  # hours

[ratelimit]
requests_per_second = 10
burst = 20